export const PIZZA = "PIZZA";
export const DELETE_PIZZA = "DELETE_PIZZA";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const ADD_PIZZA = "ADD_PIZZA";
export const CATEGORY_PIZZAS = "CATEGORY_PIZZAS";
export const CATEGORY_PIZZAS_FAIL = "CATEGORY_PIZZAS_FAIL";
